spring:
  application:
    name: TextToSpeech
  thymeleaf:
    cache: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration

server:
  servlet:
    context-path: /tts